config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root to: "home#index"
   resources :subcategories
   resources :categories 
   resources :orders do
      collection do
                  post '/select_category',    to: 'orders#select_category'
                  post '/select_subcategory', to: 'orders#select_subcategory'
                  post '/select_product',     to: 'orders#select_product'
       end
   end
   resources :products do
    collection do
      post '/select_category', to: 'products#select_category'
      post '/select_subcategory', to: 'products#select_subcategory'
   end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ApplicationRecord
  
  has_many :subcategories, dependent: :delete_all

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :integer          not null, primary key
#  quantity   :integer
#  cost       :decimal(, )      not null
#  user_id    :integer          not null
#  product_id :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Order < ApplicationRecord
  
  validates :quantity, :cost, :user_id, :product_id, presence: true
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id             :integer          not null, primary key
#  name           :string           not null
#  photo          :string
#  quantity       :integer
#  price          :decimal(, )
#  packsize       :integer
#  subcategory_id :integer          not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#


class Product < ApplicationRecord
    
  belongs_to :subcategory
  has_many :orders
  has_many :users, through: :orders
  validates :name, :price, :quantity ,  presence: true
  validates :name, uniqueness: { scope: [:name, :packsize ,:subcategory_id] }
end

app/models/subcategory.rb
# == Schema Information
#
# Table name: subcategories
#
#  id          :integer          not null, primary key
#  name        :string           not null
#  category_id :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Subcategory < ApplicationRecord
    
  belongs_to :category
  has_many :products, dependent: :delete_all
  validates :name ,  presence: true
  validates :name, uniqueness: { scope: [:name, :category_id] }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  role                   :string           default("user")
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :orders
  has_many :products, through: :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :get_user

  private

  def get_user
    @user = current_user
    @is_logged_in = user_signed_in?
    @is_user = @is_logged_in && @user.role == 'user'
    @is_admin = @is_logged_in && @user.role == 'admin'
  end

  def auth_admin
    redirect_to root_url if !@is_admin
  end

  def auth_user
    redirect_to root_url if !@is_user
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    
  before_action :auth_admin

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
      
    @category = Category.new(params[:category].permit(:name))
    if @category.save
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def destroy
      category = Category.find(params[:id])
      category.destroy
      redirect_to categories_path
  end

  def show
    @category = Category.find(params[:id])
   
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    
  before_action :auth_user
  
  def new
    @categories = Category.all
    @order = Order.new
  end
  
  def index
    
     @orders = @user.orders
  end
  

def select_category
    @category = Category.find(params[:category_id])
    @subcategories = @category.subcategories
    render 'new'
  end

  def select_subcategory
   
    @category = Category.find(params[:category_id])
    @subcategory = Subcategory.find(params[:subcategory_id])
    @products = @subcategory.products
    render 'new'
  end
  
  def select_product
    @subcategory = Subcategory.find(params[:subcategory_id])
    @product = Product.find(params[:product_id])
    @order = Order.new
    render 'new'
  end
  
  
  def create 
    
    @subcategory = Subcategory.find(params[:order][:subcategory_id])
    @product = Product.find(params[:order][:product_id])
    @order = Order.new(params[:order].permit(:user_id , :product_id))
     
     ordqty = (params[:order][:quantity]).to_i
     totalqty = @product.quantity
      
        if  (ordqty < totalqty) then
            @order.quantity = ordqty
            @order.cost = @product.price * ordqty
            @order.user_id = @user.id
            
            if @order.save
              redirect_to orders_path
            else
               @product = Product.find(params[:order][:product_id])
              render 'new'
            end
        
        else
          
          @order.errors.add(:order, 'order qty exceeds available qty') 
          @product = Product.find(params[:order][:product_id])
          render 'new'
        end
 end

  def destroy
      order = Order.find(params[:id])
      order.destroy
      redirect_to orders_path
      
  end

  def show
    
   
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    
  before_action :auth_admin

  def index
    @products = Product.all
  end

  def new
    @categories = Category.all
   
    @product = Product.new
    
  end


def select_category
    @category = Category.find(params[:category_id])
    @subcategories = @category.subcategories
    render 'new'
  end

  def select_subcategory
    
    @product = Product.new
    @category = Category.find(params[:category_id])
    @subcategory = Subcategory.find(params[:subcategory_id])

    render 'new'
  end
  
  
  def create
    @product = Product.new(params[:product].permit(:name ,:price , :packsize , :quantity, :subcategory_id , :photo))
    if @product.save
      redirect_to products_path
    else
      render 'new'
    end
  end

  def destroy
    
      product = Product.find(params[:id])
      product.destroy
      redirect_to products_path
      
  end

  def show
    
   
  end
  
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
    
  before_action :auth_admin

  def index
    @categories = Category.all
    @subcategories = Subcategory.all
  end

  def new
    @categories = Category.all
    @subcategory = Subcategory.new
  end

  def create
      
    @subcategory = Subcategory.new(params[:subcategory].permit(:name , :category_id))
    if @subcategory.save
      redirect_to subcategories_path
    else
      render 'new'
    end
  end

  def destroy
    
      subcategory = Subcategory.find(params[:id])
      subcategory.destroy
      redirect_to subcategories_path
      
  end

  def show
    
   
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_alerts.html.erb
<% if notice || alert %>
  <div class="border border-warning rounded p-2 m-2">
    <h4>Authentication</h4>
    <p class="text-info"><%= notice %></p>
    <p class="text-danger"><%= alert %></p>
  </div>
<% end %>

app/views/application/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="border border-danger rounded p-2">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li class="text-danger"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/application/_footer.html.erb
<nav class="navbar fixed-bottom navbar-dark bg-dark">
  <span class="navbar-text">
      (c) Mckesson Corp
  </span>
</nav>

app/views/application/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" href="/">MckDrug</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if !@is_logged_in %>
        <li class="nav-item">
          <a class="nav-link" href="/users/sign_in"><i class="fa fa-recycle"></i> Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/users/sign_up"><i class="fa fa-plus-circle"></i> Register</a>
        </li>
      <% elsif @is_admin %>
        <li class="nav-item">
          <a class="nav-link" href="/categories"><i class="fa fa-medkit"></i> Add Category</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="/subcategories"><i class="fa fa-stethoscope"></i> Add SubCategory</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/products"><i class="fa fa-user-md"></i> Add Product</a>
        </li>
      <% elsif @is_user %>
        <li class="nav-item">
          <a class="nav-link" href="/orders"><i class="fa fa-user-md"></i> Order Now!</a>
        </li>
      <% end %>

      <% if @is_logged_in %>
        <li class="nav-item">
          <a class="nav-link" href="/users/edit"><i class="fa fa-id-card"></i> Profile</a>
        </li>
        <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
            <i class="fa fa-window-close"></i> <%= "#{@user.email} (#{@user.role})" %>
          <% end %>
        </li>
      <% end %>
  </div>
</nav>

app/views/categories/index.html.erb
<h1 class="display-4 p-2">Ships</h1>

<a href="/ships/new" class="btn btn-outline-primary m-2">
  <i class="fa fa-plus-circle"></i> Add Category </a>

<table class="table table-striped">
  <thead class="thead-inverse">
    <tr>
      <th></th>
      <th>Id</th>
      <th>Name</th>
      </tr>
  </thead>
  <tbody>
    <% @categories.each do |c| %>
      <tr>
        <td>
          <%= link_to category_path(s), method: :delete do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
        </td>
        <td><%= link_to c.id, category_path(s) %></td>
        <td><%= s.name %></td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<h1 class="display-4 p-2">Add Category</h1>

<div class="row">
  <div class="col-4">
    <%= form_with(model: @category, local: true) do |form| %>

      <%= render 'errors', object: @category %>

      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, id: :category_name, class: 'form-control' %>
      </div>


      <div class="form-group">
        <%= form.submit class: 'btn btn-outline-primary' %>
      </div>
    <% end %>
  </div>
  <div class="col-8"></div>
</div>

app/views/home/index.html.erb
Welcome to Mckesson "Better" Connect !

We promise , it works :)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mckdrug</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

   <body>
    <%= render 'nav' %>
    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <div style="margin-bottom: 100px;">
            <%= render 'alerts' %>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
    <%= render 'footer' %>
  </body>
</html>

app/views/orders/index.html.erb
<h1 class="display-4 p-2"> All Orders </h1>

<a href="/orders/new" class="btn btn-outline-primary m-2">
  <i class="fa fa-plus-circle"></i> Place an Order </a>

<table class="table table-striped">
  <thead class="thead-inverse">
    <tr>
      <th></th>
      <th>Id</th>
      <th>Drug</th>
      <th>Quantity</th>
      <th>Cost</th>
      <th>Photo</th>
      </tr>
  </thead>
  <tbody>
    <% @orders.each do |s| %>
      <tr>
        <td>
          <%= link_to order_path(s), method: :delete do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
        </td>
        
        <td><%= s.id %></td>
        <td><%= s.product.name  %></td>
        <td><%= s.quantity %></td>
        <td><%= number_to_currency s.cost %></td>
         <td><%= image_tag(s.product.photo, width: 75, height: 75, class: 'img-thumbnail') if s.product.photo %></td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/orders/new.html.erb
<h1 class="display-4 p-2">Place an Order</h1>

<% if @categories %>
      <div class="row">
          <div class="col-4">
            <%= form_with(url: select_category_orders_path, local: true, method: :post) do |form| %>
      
              <div class="form-group">
                <%= form.label :category_id %>
                <%= form.collection_select(:category_id, @categories, :id, :name, {}, {class: 'form-control'}) %>
              </div>
      
              <div class="form-group">
                <%= form.submit 'Select Category', class: 'btn btn-outline-primary' %>
              </div>
            <% end %>
          </div>
          <div class="col-8"></div>
        </div>

<% elsif @subcategories  %>
      <div class="row">
          <div class="col-4">
            <%= form_with(url: select_subcategory_orders_path, local: true, method: :post) do |form| %>
      
              <%= form.hidden_field(:category_id, value: @category.id) %>
      
              <div class="form-group">
                <%= form.label :subcategory_id %>
                <%= form.collection_select(:subcategory_id, @subcategories, :id, :name, {}, {class: 'form-control'}) %>
              </div>
      
              <div class="form-group">
                <%= form.submit 'Select Sub Category', class: 'btn btn-outline-primary' %>
              </div>
            <% end %>
          </div>
          <div class="col-8"></div>
        </div>
  
  <% elsif @products  %>
      <div class="row">
          <div class="col-4">
            <%= form_with(url: select_product_orders_path, local: true, method: :post) do |form| %>
      
              <%= form.hidden_field(:category_id, value: @category.id) %>
              <%= form.hidden_field(:subcategory_id, value: @subcategory.id) %>
      
      
              <div class="form-group">
                <%= form.label :product_id %>
                <%= form.collection_select(:product_id, @products, :id, :name, {}, {class: 'form-control'}) %>
              </div>
      
              <div class="form-group">
                <%= form.submit 'Select Product', class: 'btn btn-outline-primary' %>
              </div>
            <% end %>
          </div>
          <div class="col-8"></div>
        </div>
  
  <% elsif @order  %>
    <div class="row">
        <div class="col-4">
          <%= form_with(model: @order, local: true) do |form| %>

           <%= render 'errors', object: @order %>
          
           
            <%= form.hidden_field(:subcategory_id, value: @subcategory.id) %>
            <%= form.hidden_field(:product_id, value: @product.id) %>
          
            
            <div class="form-group">
              <%= form.label :quantity %>
               <%= form.text_field :quantity, id: :order_quantity, class: 'form-control' %>
            </div>
    
            <div class="form-group">
              <%= form.submit 'Place Order', class: 'btn btn-outline-primary' %>
            </div>
          <% end %>
        </div>
        <div class="col-8"></div>
      </div>
  <%end%>

app/views/products/index.html.erb
<h1 class="display-4 p-2"> Products</h1>

<a href="/products/new" class="btn btn-outline-primary m-2">
  <i class="fa fa-plus-circle"></i> Add Product </a>

<table class="table table-striped">
  <thead class="thead-inverse">
    <tr>
      <th></th>
      <th>Category</th>
      <th>SubCategory</th>
      <th>Id</th>
      <th>Name</th>
      <th>Price</th>
      <th>PackSize</th>
      <th>Quantity</th>
      <th>Photo</th>
      </tr>
  </thead>
  <tbody>
    <% @products.each do |s| %>
      <tr>
        <td>
          <%= link_to product_path(s), method: :delete do %>
            <i class="fa fa-trash-o"></i>
          <% end %>

        </td>
        <td><%= s.subcategory.category.name  %></td>
        <td><%= s.subcategory.name  %></td>
        <td><%= s.id %></td>
        <td><%= s.name %></td>
        <td><%= number_to_currency s.price %></td>
        <td><%= s.packsize %></td>
        <td><%= s.quantity %></td>
         <td><%= image_tag(s.photo, width: 75, height: 75, class: 'img-thumbnail') if s.photo %></td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1 class="display-4 p-2">Add Products</h1>

<% if @categories %>
<div class="row">
    <div class="col-4">
      <%= form_with(url: select_category_products_path, local: true, method: :post) do |form| %>

        <div class="form-group">
          <%= form.label :category_id %>
          <%= form.collection_select(:category_id, @categories, :id, :name, {}, {class: 'form-control'}) %>
        </div>

        <div class="form-group">
          <%= form.submit 'Select Category', class: 'btn btn-outline-primary' %>
        </div>
      <% end %>
    </div>
    <div class="col-8"></div>
  </div>

<% elsif @subcategories  %>
<div class="row">
    <div class="col-4">
      <%= form_with(url: select_subcategory_products_path, local: true, method: :post) do |form| %>

        <%= form.hidden_field(:category_id, value: @category.id) %>

        <div class="form-group">
          <%= form.label :subcategory_id %>
          <%= form.collection_select(:subcategory_id, @subcategories, :id, :name, {}, {class: 'form-control'}) %>
        </div>

        <div class="form-group">
          <%= form.submit 'Select Sub Category', class: 'btn btn-outline-primary' %>
        </div>
      <% end %>
    </div>
    <div class="col-8"></div>
  </div>
  
  <% elsif @product %>
  
<div class="row">
  <div class="col-4">
    <%= form_with(model: @product, local: true) do |form| %>

      <%= render 'errors', object: @product %>

        <%= form.hidden_field(:category_id, value: @category.id) %>
        <%= form.hidden_field(:subcategory_id, value: @subcategory.id) %>

      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, id: :product_name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= form.label :price %>
        <%= form.text_field :price, id: :product_price, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= form.label :packsize %>
        <%= form.text_field :packsize, id: :product_packsize, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= form.label :quantity %>
        <%= form.text_field :quantity, id: :product_quantity, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= form.label :photo %>
        <%= form.text_field :photo, id: :product_photo, class: 'form-control' %>
      </div>
      

      <div class="form-group">
        <%= form.submit class: 'btn btn-outline-primary' %>
      </div>
    <% end %>
  </div>
  <div class="col-8"></div>
</div>

<% end %>

app/views/subcategories/index.html.erb
<h1 class="display-4 p-2"> Sub Categories</h1>

<a href="/subcategories/new" class="btn btn-outline-primary m-2">
  <i class="fa fa-plus-circle"></i> Add SubCategory </a>

<table class="table table-striped">
  <thead class="thead-inverse">
    <tr>
      <th></th>
      <th>Category</th>
      <th>SubCategory</th>
      </tr>
  </thead>
  <tbody>
    <% @subcategories.each do |s| %>
      <tr>
        <td>
          <%= link_to subcategory_path(s), method: :delete do %>
            <i class="fa fa-trash-o"></i>
          <% end %>

        </td>
        <td><%= s.category.name  %></td>
        <td><%= s.name %></td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/subcategories/new.html.erb
<h1 class="display-4 p-2">Add SubCategory</h1>

<div class="row">
  <div class="col-4">
    <%= form_with(model: @subcategory, local: true) do |form| %>

      <%= render 'errors', object: @subcategory %>

     <div class="form-group">
        <%= form.label :category_id %>
        <%= form.collection_select(:category_id, @categories, :id, :name, {}, {class: 'form-control'}) %>
      </div>

      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, id: :subcategory_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.submit class: 'btn btn-outline-primary' %>
      </div>
    <% end %>
  </div>
  <div class="col-8"></div>
</div>